{
 "title": "Monitorización_Proyecto",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "description": "Memory Usage (%)",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\r\n/ node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[2m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "description": "Disk Usage (%)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\r\n- node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"})\r\n/ node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}